packages:
  - "apps/*"
  - "libs/*"
  - "e2e/*"
  - "tests/*"
  - "libs/coin-modules/*"
  - "libs/ledgerjs/**"
  - "libs/ledger-services/**"
  - "libs/ui/packages/*"
  - "libs/ui/examples/*"
  - "libs/ledger-live-common/tools"
  - "tools/**"
  - "docs"
